### ISSUE TITLE
Crashes on postmarketOs

### ISSUE THREAD

**Issue by Spagett1** [JasonG-FR/PineBattery#9]
when running on sxmo postmarketOs edge with python 3.10.5 i get the following error when launching. 

```
Traceback (most recent call last):
  File "/home/spagett/.local/share/PineBattery/PineBattery.py", line 226, in <module>
    main()
  File "/home/spagett/.local/share/PineBattery/PineBattery.py", line 219, in main
    builder.connect_signals(App(builder))
  File "/home/spagett/.local/share/PineBattery/PineBattery.py", line 44, in __init__
    self.temperature_values = init_temp_sensors()
  File "/home/spagett/.local/share/PineBattery/PineBattery.py", line 208, in init_temp_sensors
    chips = sorted([chip for chip in sensors() if "cpu" in chip or "gpu" in chip])
  File "/home/spagett/.local/share/PineBattery/PineBattery.py", line 199, in sensors
    task = subprocess.Popen(["sensors", "-j"], stdout=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sensors'
```

**Comment by JasonG-FR** [comment]
Looks like the `lm_sensors` package is missing. 

I'm unable to try it on PmOS right now, but it being based on Alpine this might work : https://wiki.alpinelinux.org/wiki/Setting_up_lm_sensors 

If that's the issue, I'll add `lm_sensors` as a dependency on the README.
